### ISSUE TITLE
EPZG

### ISSUE THREAD

**Issue by SP-NTX** [Klaudiae/FGCompanion-PolandEnhanced#1]
Do you want to help with EPZG? i live near EPZG and im 3D modeller. Also, why everything to one addon? its bad idea...
; Edit: i can't help with it :(

**Comment by Klaudiae** [comment]
1) It's totally fine, I'd have to reject that offer as im only remaking the scenery in terms of messing with the files, not actually adding or removing any objects etc. and i have no experience in that whatsoever. And about everything being in one addon - as i finish adding all the airports I will most probably make it possible for each and every airport to be downloaded seperetaly, as of now the only way of getting the scenery is to get the whole thing however. Thanks for willing to contribute tho, cheers!
